### ISSUE TITLE
UI distortion

### ISSUE THREAD

**Issue by gaurangkeluskar22** [Chinmay2660/ui-clashofclans#1]
Ui gets distorted on mobile devices 

![image](https://github.com/Chinmay2660/ui-clashofclans/assets/43683829/adfea9fb-feb9-449c-9ca0-63753c46cc09)

**Comment by gaurangkeluskar22** [comment]
Hi @Chinmay2660 , Please assign this issue to me.

**Comment by Chinmay2660** [comment]
@gaurangkeluskar22 assigned you
