### ISSUE TITLE
When user clicks on logo it is not redirecting user to Homepage

### ISSUE THREAD

**Issue by gaurangkeluskar22** [Chinmay2660/ui-clashofclans#3]
**Issue:**
When user clicks on logo it is not redirecting user to Homepage

**Demo:**

https://github.com/user-attachments/assets/d3205d86-4bec-45f3-b4a0-974bab49998e

**Comment by gaurangkeluskar22** [comment]
Hi @Chinmay2660, can you please assign this issue to me, would love to contribute

**Comment by Chinmay2660** [comment]
Hi @gaurangkeluskar22, I’ve decided to stop working on this repo, so I’ll be closing this issue
